version: '3.1'

services:
  node-helloworld:
        build: ../node-app
        restart: always

  mongo:
    build: ../mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  reverseproxy:
        build: ../nginx
        ports:
            - 8080:3000
            - 8081:8081
        restart: always
  
